name: Semver from branch name
description: Semver updates

inputs:
  token:
    description: secrets.GITHUB_TOKEN
    required: true
  patch-pattern:
    description: pattern
    required: false
    default: fix
  minor-pattern:
    description: pattern
    required: false
    default: feat
  major-pattern:
    description: pattern
    required: false
    default: upgrade

outputs:
  semver:
    description: Next version name

runs:
  using: 'node16'
  main: "build/index.js"
