on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Action
        uses: ./.github/actions/calculate-version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
