name: Quality checks

on:
  pull_request:

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install
        run: npm ci

      - name: Unit tests
        run: npm run test

      - name: Lint
        run: npm run lint
