name: Testing

on:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Release
        run: |
          npm ci
          npm run test
